# <center><font color="brown">one variable is unknown</font></center>

$$\hat{y}=\it{b}+\it{m}\times x$$

* $\hat{y}$ : predicated height，$\it{b}$ : intercept，$\it{m}$ : slope，$\it{x}$ : input weight。The residual equation can be shown below.
>
>$$Res=y-\hat{y}$$

* Assume that $m=0.64$ (i.e., slope is known). Initially, pick a random value for $b$. Assume that $b$ is set to be zero.
>
> * When (x,y)=(0.5, 1.4),
> $$Res=y-\hat{y}=1.4-(0.64\times 0.5)=1.1$$
> * When (x,y)=(2.3, 1.9),
> $$Res=y-\hat{y}=1.9-(0.64\times 2.3)=0.4$$
> * When (x,y)=(2.9, 3.2),
> $$Res=y-\hat{y}=3.2-(0.64\times 2.9)=1.3$$

* The sum of squared residuals (SSR) is
> $1.1^2 + 0.4^2 + 1.3^2 = 3.1$

* The goal is by changing $b$ value again and again to make SSR smaller. In this case, the SSR can be expressed as
>
> $SSR = (1.4 - (b+0.64\times 0.5))^2 + (1.9 - (b+0.64\times 2.3))^2 + (3.2 - (b+0.64\times 2.9))^2$

* The gradient of SSR is as follows
>
> $\frac{d(SSR)}{db} = -2((1.4 - (b+0.64\times 0.5)) \\-2(1.9 - (b+0.64\times 2.3)) \\-2(3.2 -(b+0.64\times 2.9))$

* Another term step_size is required. "step_size" is how $b$ changes between each calculation of the model. step_size at b being $\underline{b}$ is defined as
>
> $$step\_size = \alpha \times \frac{d(SSR)}{db}\Bigr|_{b=\underline{b}}$$

* Here $\alpha$ is called <em>learning rate</em>. For each calculation of the model, the value of $b$ would be updated as follows.
>
> $$b_{new}=b_{old}-step\_size=b_{old}-\alpha \times \frac{d(SSR)}{db}\Bigr|_{b=b_{old}} $$

* Obviously, when $\frac{d(SSR)}{db}\Bigr|_{b=b_{old}}$ is negative, $b_{new}$ should be larger than $b_{old}$. On the other hand, when $\frac{d(SSR)}{db}\Bigr|_{b=b_{old}}$ is positive, $b_{new}$ should be smaller than $b_{old}$.

<hr>

* Now, initializing `bias` and `learning rate` as $b=0，\alpha=0.1$
>
> * run 1:
>
> $$\frac{d(SSR)}{db}\Bigr|_{b=0}=-5.7$$
>
> $$step_{size}=-5.7\times 0.1=-0.57$$
>
> $$b_{new}=b_{old}-step\_size=0-(-0.57)=0.57$$
>
> * run 2:
>
> $$\frac{d(SSR)}{db}\Bigr|_{b=0.57}=-2.3$$
>
> $$step_{size}=-2.3\times 0.1=-0.23$$
>
> $$b_{new}=b_{old}-step\_size=0.57-(-0.23)=0.8$$
>
> * run 3:
>
> $$\frac{d(SSR)}{db}\Bigr|_{b=0.8}=-0.9$$
>
> $$step_{size}=-0.9\times 0.1=-0.09$$
>
> $$b_{new}=b_{old}-step\_size=0.8-(-0.09)=0.89$$
>
> * run 4:
>
> $$\frac{d(SSR)}{db}\Bigr|_{b=0.89}=-0.3$$
>
> $$step_{size}=-0.3\times 0.1=-0.03$$
>
> $$b_{new}=b_{old}-step\_size=0.89-(-0.03)=0.92$$
>
> * run 5 (skip details):
>
> $$b_{new}=0.94$$
>
> * run 6 (skip details):
>
> $$b_{new}=0.95$$

* After 6 runs, $SSR=0.95$. It is much closer to 0, compared to the $SSR=3.1$ in the first run.


## <center>Summary</center>
1. Figure out $SSR$.

2. Based on $SSR$, figure out $\frac{d(SSR)}{db}$

3. Pick a random number $\underline{b}$ as the initial value of $b$

4. Find out the slope= $\frac{d(SSR)}{db}\Bigr|_{b=\underline{b}}$

5. Then, step_size = $\alpha$ $\times$ slope

6. $b_{new}$ = $b_{old}$  - step_size

repeat the above process until step_size $<$ 0.001

# <center><font color="brown">two variables are both unknown</font></center>

$$\hat{y}=\it{b}+\it{m}\times x$$

* More generally, $m$ and $b$ are both unknown
>
> $$SSR = (1.4 - (b+m\times 0.5))^2 + (1.9 - (b+m\times 2.3))^2 + (3.2 - (b+m\times 2.9))^2$$
>
> $$MSE = \frac{1}{3}SSR$$
>
> $MSE$ is known as Loss Function.
>
* The goal is to minimize $MSE$. The gradient of $MSE$ is as follows
>
> $$\frac{\partial(MSE)}{\partial b}=\frac{1}{3}\frac{\partial(SSR)}{\partial b}$$
>
> $$\frac{\partial(MSE)}{\partial m}=\frac{1}{3}\frac{\partial(SSR)}{\partial m}$$
>
> $$\frac{\partial(SSR)}{\partial b} = -2((1.4 - (b+m\times 0.5)) \\-2(1.9 - (b+m\times 2.3)) \\-2(3.2 - (b+m\times 2.9))$$
>
> $$\frac{\partial(SSR)}{\partial m} = -2\times 0.5\times(1.4 - (b+m\times 0.5)) \\-2\times 2.3\times (1.9 - (b+m\times 2.3)) \\-2\times 2.9 \times(3.2 - (b+m\times 2.9))$$



* Pick a random number for $b$ and another number for $m$. Assume that $b$=0 and $m$=1.  
> * run 1:
> $$\frac{1}{3}\frac{\partial(SSR)}{\partial b}\Bigr|_{b=0}=-0.5333$$
> $$\frac{1}{3}\frac{\partial(SSR)}{\partial m}\Bigr|_{m=1}=-0.2667$$
>
> $$step\_size_b = -0.5333\times(0.01)$$
> $$step\_size_m = -0.2667\times(0.01)$$
>
> $$b_{new} = 0-(-0.0053)=0.0053$$
> $$m_{new} = 1-(-0.0026)=1.0027$$
>
> * run 2:
> $$\frac{1}{3}\frac{\partial(SSR)}{\partial b}\Bigr|_{b=0.016}=-0.5125$$
> $$\frac{1}{3}\frac{\partial(SSR)}{\partial m}\Bigr|_{m=1.008}=-0.2216$$
>
> $$step\_size_b = -0.5125\times(0.01)$$
> $$step\_size_m = -0.2216\times(0.01)$$
>
> $$b_{new} = 0.0053-(-0.005125)=0.0105$$
> $$m_{new} = 1.0027-(-0.002216)=1.0049$$
>
> * After much more runs:
>
> $$b_{new} = 0.95$$
> $$m_{new} = 0.64$$


## Conslusion

* Step 1: Find out $SSR$ and list variable parameters (e.g., $b_1\ldots m_1\ldots $). Figure out the gradient formulas $\bigstar$ of $SSR$ (e.g., $\frac{\partial (SSR)}{\partial b_1}\ldots \frac{\partial (SSR)}{\partial m_1}\ldots $)

* Step 2: Pick random values for those variable parameters (e.g., $b_1\ldots m_1\ldots $)

* Step 3: Plug those values in Step 2 into $\bigstar$ to obtain the slope

* Step 4: Find out $step\_size= \alpha\times slope$

* Step 5: Update the values for all the variable parameters
> $$b_i^{new} = b_i^{new}$$
> $$\vdots$$
> $$m_i^{new} = m_i^{new}$$
> $$\vdots$$

Repeat Step 3 $\sim$ Step 5 until $step_size$ $<$ a very small number

# <font color="brown">PyTorch 操作示範</font>

In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# known input data
inputs = np.array([[0.5],
           [2.3],
           [2.9]],
           dtype='float32')
targets = np.array([[1.4],
            [1.9],
            [3.2]],
            dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
# set up the initial values for w and b
w = torch.Tensor([[1]]).requires_grad_(True)
b = torch.Tensor([[0]]).requires_grad_(True)

w, b

(tensor([[1.]], requires_grad=True), tensor([[0.]], requires_grad=True))

In [ ]:
# define the linear regresssion model
def model(x):
    return x @ w.t() + b

In [ ]:
# define the loss function, based on the mean squared error (MSE).
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [ ]:
# before training, one can take a look at the initial loss value
loss = mse(model(inputs), targets)
loss
# Notes that, based on the initial values of w and b,
# mse(inputs, targets) = mse(model(inputs), targets). Since w=1 and b=0, model(inputs)=inputs
# [(0.5-1.4)^2 + (2.3-1.9)^2 + (2.9-3.2)^2]/3 = 0.3533

tensor(0.3533, grad_fn=<DivBackward0>)

## run 1

In [ ]:
"""計算損失"""
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(0.3533, grad_fn=<DivBackward0>)

In [ ]:
"""對損失函數求導"""
loss.backward()

In [ ]:
"""Gradients for weights (第1輪)"""

print("del loss / del w = ",w.grad) # 或 print(w.grad.data)
print("del loss / del b = ",b.grad) # 或 print(b.grad.data)

del loss / del w =  tensor([[-0.2667]])
del loss / del b =  tensor([[-0.5333]])


In [ ]:
"""更新 w, b"""
with torch.no_grad():
  w -= w.grad * 1e-2
  b -= b.grad * 1e-2
  w.grad.zero_()
  b.grad.zero_()

In [ ]:
"""(第1輪)顯示w, b更新後的結果"""
print(w)
print(b)

tensor([[1.0027]], requires_grad=True)
tensor([[0.0053]], requires_grad=True)


In [ ]:
"""顯示一下，最新的預測結果，對比真實結果"""
preds = model(inputs)
print(preds)  # 預測結果
print(targets) # 真實結果

tensor([[0.5067],
        [2.3115],
        [2.9131]], grad_fn=<AddBackward0>)
tensor([[1.4000],
        [1.9000],
        [3.2000]])


## run2

In [ ]:
"""計算損失"""
loss = mse(preds, targets)
print(loss)

tensor(0.3499, grad_fn=<DivBackward0>)


In [ ]:
"""對損失函數求導"""
loss.backward()

In [ ]:
"""Gradients for weights (第2輪)"""
print("del loss / del w = ",w.grad) # 或 print(w.grad.data)
print("del loss / del b = ",b.grad) # 或 print(b.grad.data)

del loss / del w =  tensor([[-0.2216]])
del loss / del b =  tensor([[-0.5125]])


In [ ]:
"""更新 w, b"""
with torch.no_grad():
  w -= w.grad * 1e-2
  b -= b.grad * 1e-2
  w.grad.zero_()
  b.grad.zero_()

In [ ]:
"""(第2輪)顯示w, b更新後的結果"""
print(w)
print(b)

tensor([[1.0049]], requires_grad=True)
tensor([[0.0105]], requires_grad=True)


In [ ]:
"""顯示一下，最新的預測結果，對比真實結果"""
preds = model(inputs)
print(preds)  # 預測結果
print(targets) # 真實結果

tensor([[0.5129],
        [2.3217],
        [2.9246]], grad_fn=<AddBackward0>)
tensor([[1.4000],
        [1.9000],
        [3.2000]])


## run 3 ~ run 1000

In [ ]:
# continue to train the model (run 998 times)
for i in range(998):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-2
    b -= b.grad * 1e-2
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
# check the slope, the intercept, the loss value and the predicted values
preds = model(inputs)
loss = mse(preds, targets)

print("slope:\t",w.item())
print("intercept:",b.item())
print("loss:",loss.item())
print(preds)

slope:	 0.6497616767883301
intercept: 0.9282135367393494
loss: 0.14829975366592407
tensor([[1.2531],
        [2.4227],
        [2.8125]], grad_fn=<AddBackward0>)


錯誤更新 w, b
```python
w.retain_grad()
b.retain_grad()
w -= w.grad * 1e-2
b -= b.grad * 1e-2

with torch.set_grad_enabled(is_train):
  w.grad.zero_()
```  

# 計算工具(備份)


```python
def funcb(m, b):
  return -2*(1.4 - ( b + m * 0.5)) - 2*(1.9 - ( b + m * 2.3)) - 2*(3.2 - ( b + m * 2.9))

def funcm(m, b):
  return -2*0.5*(1.4 - ( b + m * 0.5)) - 2*2.3*(1.9 - ( b + m * 2.3)) - 2*2.9*(3.2 - ( b + m * 2.9))

funcb(1,0)/3, funcm(1,0)/3
print('%.4f' %(funcb(1.0027,0.0053)/3))
print('%.4f' %(funcm(1.0027,0.0053)/3))
```

