In [ ]:
class A(object):
  a = 'a'

  def foo1(name):
    print('hello', name)

  def foo2(self, name):
    print('hello!', name)

  def foo3(cls, name):
    print('hello!!', name)

In [ ]:
class Student():
    cnt = 0 # 這個變數是屬於整個Student類別的
    def __init__(self, name, score):
        Student.cnt += 1 # 每次新開一個Student的物件，計數器就會+1
        self.name = name
        self.score = score

    def readMyName(self):
        print('聽清楚了，我的名字是' + self.name + '!!!')

    def compare(self, b):
        diff = sum(self.score.values()) - sum(b.score.values())
        # 有冒號的式子如果底下程式碼只有一行，也可以選擇直接和判斷式寫成同一行
        if diff > 0: print(self.name + '贏了！')
        elif diff == 0: print('什麼？竟然平手？！')
        else: print('可...可惡，難道，這就是' + b.name + '真正的實力嗎？')

    @classmethod
    def getCount(cls):
        print('目前的學生總數：%d' % cls.cnt)

In [ ]:
Student.getCount()

目前的學生總數：0


In [ ]:
ming = Student('阿明', {'數學':55, '英文':70, '物理':55})
ming.readMyName()
Student.getCount()

聽清楚了，我的名字是阿明!!!
目前的學生總數：1


In [ ]:
ming.score

{'數學': 55, '英文': 70, '物理': 55}

In [ ]:
mei = Student('小美', {'數學':90, '英文':88, '物理':100})

howhow = Student('HowHow', {'數學':80, '英文':60, '物理':40})

Student.getCount()

目前的學生總數：3


In [ ]:
class Desolve():
    @staticmethod
    def ads():
        print('無情工商時間!')
        print('從LeetCode學演算法是一系列非常好的課程!')
        print('https://bit.ly/leetcodeall')

Desolve.ads()

無情工商時間!
從LeetCode學演算法是一系列非常好的課程!
https://bit.ly/leetcodeall


In [ ]:
class nmod3():
    def __init__(self, num):
        self.num = num

    def __eq__(self, n2): # 定義 "=="這個運算子為是否除以3的餘數相同
        return self.num % 3 == n2.num % 3

a = nmod3(11) # 除以3餘2
b = nmod3(18) # 除以3餘0
c = nmod3(17) # 除以3餘2

print(a == b)
print(a == c)
print(b == c)

False
True
False


In [ ]:
print(a)

In [ ]:
%%writefile kk.py
__all__=('A','func')
class A():
  def __init__(self,name,age):
    self.name=name
    self.age=age
class B():
  def __init__(self,name,id):
    self.name=name
    self.id=id
def func():
  print( 'func() is called! ')
def func1():
  print( 'func1() is called! ')

Overwriting kk.py


In [ ]:
from kk import * #由於kk.py中沒有定義__all__屬性，所以匯入了kk.py中所有的公有屬性、方法、類
a=A('python','24')
print(a.name,a.age)
b=B('python',123456)
print(b.name,b.id)
func()
func1()

python 24
python 123456
func() is called! 
func1() is called! 


In [ ]:
%%writefile kk1.py
import sys # 真的需要建立一個sys的包或檔案
__all__ = ["func","sys"]
def func():
  print( 'func() is called!' )
def _func():
  print( '_func() is called!')
def __func():
  print( '__func() is called!' )

Overwriting kk1.py


In [ ]:
#test_kk.py
from kk1 import func,_func,__func #可以通過這種方式匯入public,protected,private
func()
_func() #NameError: name '_func' is not defined
__func() #NameError: name '__func' is not defined

func() is called!
_func() is called!
__func() is called!


In [ ]:
class Modelt():
  def __init__(self,name,age):
    self.name=name
    self.age=age

  # def __str__(self):
  #   return self.name+str(self.age)

In [ ]:
md = Modelt('Henry Hsu',35)

In [ ]:
print(md)

Henry Hsu35


In [ ]:
print(md)

# [葉子張量和非葉子張量](https://www.modb.pro/db/542980)
連結已失效

## case 1-1

In [1]:
import torch
# 此時w1是葉子張量
w1 = torch.ones(10, requires_grad=True)

with torch.no_grad():
  w1 *= 0.5


w2 = torch.ones(10, requires_grad=True)

wto = torch.exp(w1)*w2

loss = wto.sum()
loss.backward()

```python
print(w1.is_leaf)
print(w2.is_leaf)
# w1 與 w2 都是葉節點

print(w1.grad)
print(w2.grad)
```
True

True

tensor([1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487,
        1.6487])

tensor([1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487,
        1.6487])

## case 1-2



In [7]:
# 可改成 (此時w1不是葉子張量)
w1 = torch.ones(10, requires_grad=True)*0.5

w2 = torch.ones(10, requires_grad=True)

# wto = torch.exp(w1)*w2

# loss = wto.sum()
# loss.backward()

In [8]:
print(w1.is_leaf) # w1 是非葉節點
print(w2.is_leaf) # w2 是葉節點

print(w1.grad)
print(w2.grad)

False
True
None
None


<ipython-input-8-487a018ae770>:4: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(w1.grad)




```python
print(w1.is_leaf) # w1 是非葉節點
print(w2.is_leaf) # w2 是葉節點

print(w1.grad)
print(w2.grad)
```
False

True

None

tensor([1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487, 1.6487,
        1.6487])

...


# [詳解Pytorch中的requires_grad、葉子節點與非葉子節點](https://blog.csdn.net/qq_36429555/article/details/118657440)

## case 2-1

In [24]:
a=torch.tensor([1.0], requires_grad=True) # 是葉子

b=a+1 # 不是葉子

print(a.is_leaf)
print(a.requires_grad) # 明確設定是True
print(b.is_leaf)
print(b.requires_grad) #


b.retain_grad() # b不是葉子，反向求導時若要使用.grad去顯示，必需要使用retain_grad()
b.backward()
print(b.grad)

True
True
False
True tensor([1.])


In [21]:
a=torch.tensor([1.0]) # 是葉子

b=a+1 # 依然是葉子，因為不需要對a求導，所以反向求導時，a節點變得沒有意義

print(a.is_leaf)
print(a.requires_grad) # 是False(沒設定是True)
print(b.is_leaf)    # 注意，是True
print(b.requires_grad) #

# 注意，b是葉子，所以b不能調用backward()，此例子很特殊，因為沒有非葉子節點

True
False
True
False


## case 2-2
https://blog.csdn.net/qq_27825451/article/details/95498211

http://nysdy.com/post/pytorch_detach_data/

In [58]:
a=torch.tensor([1.0], requires_grad=True) # 是葉子

b=a.sigmoid()
# b=a+1 # 不同的運算式

c = b.detach()

"""與detach有關"""
# c.requires_grad = True
# c.sum().backward() # 如果沒加上一行，單單這一行會出現錯誤，用這個分離出來的tensor去求導，會影響backward()，所以出現錯誤

"""與detach無關"""
b.sum().backward()


print(a.grad)

tensor([0.1966])


In [47]:
"""錯誤示範"""
a=torch.tensor([1.0], requires_grad=True) # 是葉子
print(a.grad)
b=a.sigmoid() # 注意這裡是用.sigmoid(), 如果b=a+1，後面的c進行in place操作，並不會出錯(Why?)
print(b)

c = b.detach()
print(c)
c.zero_() # 使用in-place操作，對c修改，這會會影響backward()，所以出現錯誤

print(c)
print(b)

b.sum().backward()

print(a.grad)

None
tensor([0.7311], grad_fn=<SigmoidBackward0>)
tensor([0.7311])
tensor([0.])
tensor([0.], grad_fn=<SigmoidBackward0>)


RuntimeError: ignored

In [57]:
""".detach改用.data，backward不會出錯，因為.data後的修改不會被autograd追蹤，但卻得到錯誤的backward"""
a=torch.tensor([1.0], requires_grad=True) # 是葉子
print(a.grad)
b=a.sigmoid()
print(b)

c = b.data # 改變c，autograd不會追蹤到，所以不會報錯
print(c)
c.zero_()

print(c)
print(b)

b.sum().backward()

print(a.grad) # 結果被影影到



None
tensor([0.7311], grad_fn=<SigmoidBackward0>)
tensor([0.7311])
tensor([0.])
tensor([0.], grad_fn=<SigmoidBackward0>)
tensor([0.])


In [60]:
"""改變sum到c.zero_()之前，backward結果就會是正確的"""
a=torch.tensor([1.0], requires_grad=True) # 是葉子
print(a.grad)
b=a.sigmoid().sum() # sum移到此
print(b)

c = b.data
print(c)
c.zero_()

print(c)
print(b)

b.backward()

print(a.grad)

None
tensor(0.7311, grad_fn=<SumBackward0>)
tensor(0.7311)
tensor(0.)
tensor(0., grad_fn=<SumBackward0>)
tensor([0.1966])


# [PyTorch的Tensor和自动求导](https://lulaoshi.info/machine-learning/neural-network/pytorch-tensor-autograd)


In [15]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()

print(x)
print(y)
print(z)
print(out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [10]:
out.backward() # 反向求導

In [12]:
print(x.grad)  # 葉節點，有求導值
print(y.grad)  # 非葉節點，求導值不保留，所以是None
print(z.grad)  # 非葉節點，求導值不保留，所以是None
print(out.grad) # 非葉節點，求導值不保留，所以是None

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
None
None
None


<ipython-input-12-68aa1dcaf5e5>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(y.grad)
<ipython-input-12-68aa1dcaf5e5>:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more inf


如果在非葉節點使用retain_grad()
```python
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()

y.retain_grad()
z.retain_grad()
out.retain_grad()

out.backward()

print(x.grad)  
print(y.grad)   
print(z.grad)  
print(out.grad)
```
tensor([[4.5000, 4.5000], <br>
     [4.5000, 4.5000]])

tensor([[4.5000, 4.5000], <br>
        [4.5000, 4.5000]])

tensor([[0.2500, 0.2500], <br>
        [0.2500, 0.2500]])
        
tensor(1.)
